/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/perfil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar el perfil del usuario autenticado */
        get: operations["AuthController_getPerfil"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/invitar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_invitarUsuario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/confirmar-invitacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_confirmarInvitacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogos/razas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogo de razas disponible para la finca
         * @description Devuelve las razas globales del sistema más las propias de la finca. Cada raza trae sus días de gestación, que es lo que MOD-03 usa para calcular la FPP.
         */
        get: operations["CatalogosController_findAllRazas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/animales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnimalesController_findAll"];
        put?: never;
        post: operations["AnimalesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/animales/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnimalesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AnimalesController_update"];
        trace?: never;
    };
    "/animales/{id}/baja": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AnimalesController_darDeBaja"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/animales/{id}/documentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar los documentos privados de un animal */
        get: operations["AnimalesController_getDocumentos"];
        put?: never;
        /** Registrar metadatos de un documento ya cargado */
        post: operations["AnimalesController_createDocumento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pesajes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PesajesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pesajes/animal/{animalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PesajesController_findAllByAnimal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tratamientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TratamientosController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tratamientos/animal/{animalId}/estado-sanitario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TratamientosController_getEstadoSanitario"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tratamientos/animal/{animalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TratamientosController_findAllByAnimal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tratamientos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["TratamientosController_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogos/medicamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener catálogo de medicamentos veterinarios del tenant */
        get: operations["SanitaryController_getMedicamentos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogos/padecimientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener catálogo de padecimientos del tenant con fármaco sugerido */
        get: operations["SanitaryController_getPadecimientos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/potreros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PotrerosController_findAll"];
        put?: never;
        post: operations["PotrerosController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/potreros/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PotrerosController_findOne"];
        put?: never;
        post?: never;
        delete: operations["PotrerosController_remove"];
        options?: never;
        head?: never;
        patch: operations["PotrerosController_update"];
        trace?: never;
    };
    "/potreros/{id}/asignar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PotrerosController_asignarAnimales"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/animales/{id}/servicios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar servicio reproductivo para un animal hembra
         * @description Registra un servicio (Inseminación Artificial o Monta Natural) y calcula los 5 hitos usando los días de gestación de la raza del animal, nunca una constante fija.
         */
        post: operations["ReproductiveController_registrarServicio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/animales/{id}/diagnosticos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar diagnóstico de preñez
         * @description Registra el resultado (Preñada o Vacía) asociado a un servicio previo. Es lo único que confirma una preñez: un servicio por sí solo no cuenta como gestante.
         */
        post: operations["ReproductiveController_registrarDiagnostico"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/animales/{id}/partos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar parto
         * @description Cierra el ciclo reproductivo y devuelve el animal a Vacía. Requiere que el animal esté en estado Preñada o En Secado. Un aborto se registra con facilidadParto = "Aborto".
         */
        post: operations["ReproductiveController_registrarParto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/animales/{id}/secados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar secado
         * @description Registra la suspensión real del ordeño, que puede diferir de la fecha de secado calculada (FPP - 60 días).
         */
        post: operations["ReproductiveController_registrarSecado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/animales/{id}/estado-reproductivo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar estado reproductivo e hitos calculados
         * @description Deriva al vuelo el estado (Vacía, Servida, Preñada, En Secado) recorriendo el historial de eventos y devuelve los próximos hitos del ciclo activo. El estado nunca se guarda ni se edita a mano.
         */
        get: operations["ReproductiveController_obtenerEstadoReproductivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/animales/{id}/eventos-reproductivos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historial reproductivo completo del animal
         * @description Lista cronológica de todos los eventos reproductivos del animal, con su detalle correspondiente. Incluye los eventos revertidos, marcados con revertido = true: el historial es append-only y una corrección tiene que poder verse.
         */
        get: operations["ReproductiveController_obtenerHistorialReproductivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reproductivo/proximos-eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calendario reproductivo de toda la finca
         * @description Hitos próximos de todas las hembras activas, ordenados por urgencia. Tipos posibles: Palpación, Secado, Aviso Parto (FPP-15), Aviso Parto Urgente (FPP-3) y Parto. Incluye los hitos vencidos en los últimos 7 días, porque siguen siendo tareas pendientes.
         */
        get: operations["ReproductiveController_obtenerProximosEventos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserProfileResponseDto: {
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            tenantId: string;
            /** @enum {string} */
            rol: "propietario" | "administrador" | "peon" | "veterinario";
            nombreCompleto: string;
            /** Format: email */
            correo: string;
            nombreFinca: string;
        };
        InviteUserDto: Record<string, never>;
        ConfirmInvitationDto: Record<string, never>;
        CreateAnimalDto: Record<string, never>;
        UpdateAnimalDto: Record<string, never>;
        BajaAnimalDto: Record<string, never>;
        DocumentoAnimalResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            animalId: string;
            tipo: string;
            archivoUrl: string | null;
            objectPath: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateDocumentoDto: {
            /**
             * @description Categoría legible del documento
             * @example Cartilla sanitaria
             */
            tipo: string;
            /**
             * @description Ruta del objeto privado dentro del bucket animal_docs
             * @example a0b9432d-cf48-4be7-a2f0-1a76c66cfcb1/b7a544c0-2ff6-4299-bbca-46fe87588386/cartilla-sanitaria/e1d67412-21d9-482f-870d-f55da282b810.pdf
             */
            objectPath: string;
        };
        CreatePesajeDto: Record<string, never>;
        CreateTratamientoDto: Record<string, never>;
        UpdateTratamientoDto: Record<string, never>;
        CreatePotreroDto: Record<string, never>;
        UpdatePotreroDto: Record<string, never>;
        AsignarAnimalesDto: Record<string, never>;
        DetalleServicioDto: {
            /** @enum {string} */
            tipoServicio: "Inseminación Artificial" | "Monta Natural";
            /** @example Titan (CRC-B-001) */
            toroOPajilla: string;
            responsable: string | null;
            /** @example 2026-06-24 */
            fpp: string;
            /** @example 2026-10-26 */
            palpacionFecha: string;
            /** @example 2026-04-25 */
            secadoFecha: string;
            /** @example 2026-06-09 */
            avisoPartoFecha: string;
            /** @example 2026-06-21 */
            avisoPartoUrgenteFecha: string;
        };
        DetalleDiagnosticoDto: {
            /** @enum {string} */
            metodo: "Palpación" | "Ecografía" | "PAG";
            /** @enum {string} */
            resultado: "Preñada" | "Vacía";
            eventoServicioId: string;
        };
        DetallePartoDto: {
            /** Format: uuid */
            eventoServicioId: string | null;
            /** Format: uuid */
            criaAnimalId: string | null;
            /** @enum {string|null} */
            facilidadParto: "Normal" | "Distocia" | "Cesárea" | "Aborto" | null;
            observaciones: string | null;
        };
        RegistrarServicioDto: {
            /**
             * @description Fecha en que se realizó el servicio (YYYY-MM-DD). No puede ser futura. Es la base del cálculo de la FPP.
             * @example 2026-09-16
             */
            fechaEvento: string;
            /**
             * @description Tipo de servicio reproductivo
             * @example Inseminación Artificial
             * @enum {string}
             */
            tipoServicio: "Inseminación Artificial" | "Monta Natural";
            /**
             * @description Nombre o código del toro, o código de pajilla utilizado
             * @example Titan (CRC-B-001)
             */
            toroOPajilla: string;
            /**
             * @description Responsable de la inseminación o técnico veterinario
             * @example Dr. Roberto García
             */
            responsable?: string;
            /**
             * @description Observaciones adicionales sobre el servicio
             * @example Celo detectado a las 6:00 AM, servicio aplicado 4:00 PM (regla AM/PM)
             */
            notas?: string;
            /**
             * @description ID del evento anterior que este nuevo evento corrige (marcará el original como revertido = true)
             * @example b7a544c0-2ff6-4299-bbca-46fe87588386
             */
            eventoCorrigeId?: string;
        };
        EventoWriteResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            animalId: string;
            /** @enum {string} */
            tipo: "SERVICIO" | "DIAGNOSTICO" | "PARTO" | "SECADO";
            /** Format: date */
            fechaEvento: string;
            /** Format: date-time */
            fechaRegistro: string;
            /** Format: uuid */
            usuarioId: string;
            revertido: boolean;
            /** Format: uuid */
            eventoCorrigeId: string | null;
            notas: string | null;
        };
        EventoServicioWriteResponseDto: {
            /** Format: uuid */
            eventoId: string;
            /** @enum {string} */
            tipoServicio: "Inseminación Artificial" | "Monta Natural";
            toroOPajilla: string;
            responsable: string | null;
            /** Format: date */
            palpacionFecha: string;
            /** Format: date */
            secadoFecha: string;
            /** Format: date */
            avisoPartoFecha: string;
            /** Format: date */
            avisoPartoUrgenteFecha: string;
            /** Format: date */
            fpp: string;
        };
        HitosReproductivosDto: {
            /** @example 2026-06-24 */
            fpp: string;
            /** @example 2026-10-26 */
            palpacionFecha: string;
            /** @example 2026-04-25 */
            secadoFecha: string;
            /** @example 2026-06-09 */
            avisoPartoFecha: string;
            /** @example 2026-06-21 */
            avisoPartoUrgenteFecha: string;
        };
        RegistrarServicioResponseDto: {
            evento: components["schemas"]["EventoWriteResponseDto"];
            servicio: components["schemas"]["EventoServicioWriteResponseDto"];
            hitos: components["schemas"]["HitosReproductivosDto"];
        };
        RegistrarDiagnosticoDto: {
            /**
             * @description Fecha en que se realizó el diagnóstico (YYYY-MM-DD). No puede ser futura.
             * @example 2026-09-10
             */
            fechaEvento: string;
            /**
             * @description ID del evento de servicio al que corresponde este diagnóstico
             * @example a0b9432d-cf48-4be7-a2f0-1a76c66cfcb1
             */
            eventoServicioId: string;
            /**
             * @description Método diagnóstico utilizado
             * @example Palpación
             * @enum {string}
             */
            metodo: "Palpación" | "Ecografía" | "PAG";
            /**
             * @description Resultado del diagnóstico de preñez
             * @example Preñada
             * @enum {string}
             */
            resultado: "Preñada" | "Vacía";
            /**
             * @description Notas o comentarios del veterinario sobre el diagnóstico
             * @example Cuerpo lúteo palpable en cuerno derecho, ~40 días de desarrollo
             */
            notas?: string;
            /** @description ID de evento anterior si este diagnóstico es una corrección */
            eventoCorrigeId?: string;
        };
        EventoDiagnosticoWriteResponseDto: {
            /** Format: uuid */
            eventoId: string;
            /** Format: uuid */
            eventoServicioId: string;
            /** @enum {string} */
            metodo: "Palpación" | "Ecografía" | "PAG";
            /** @enum {string} */
            resultado: "Preñada" | "Vacía";
        };
        RegistrarDiagnosticoResponseDto: {
            evento: components["schemas"]["EventoWriteResponseDto"];
            diagnostico: components["schemas"]["EventoDiagnosticoWriteResponseDto"];
        };
        RegistrarPartoDto: {
            /**
             * @description Fecha en que ocurrió el parto (YYYY-MM-DD). No puede ser futura.
             * @example 2026-09-10
             */
            fechaEvento: string;
            /**
             * @description ID del evento de servicio del cual se originó esta preñez
             * @example a0b9432d-cf48-4be7-a2f0-1a76c66cfcb1
             */
            eventoServicioId?: string;
            /**
             * @description ID del animal registrado como cría recién nacida (si ya fue registrado en el hato)
             * @example e1d67412-21d9-482f-870d-f55da282b810
             */
            criaAnimalId?: string;
            /**
             * @description Desenlace del parto. "Aborto" es el valor que la máquina de estados usa para cerrar la preñez sin cría viable.
             * @example Normal
             * @enum {string}
             */
            facilidadParto?: "Normal" | "Distocia" | "Cesárea" | "Aborto";
            /**
             * @description Observaciones del parto y estado de la cría y la madre
             * @example Cría hembra nacida vigorosa, 38 kg de peso al nacer
             */
            observaciones?: string;
            /** @description ID de evento anterior si este registro es una corrección */
            eventoCorrigeId?: string;
        };
        EventoPartoWriteResponseDto: {
            /** Format: uuid */
            eventoId: string;
            /** Format: uuid */
            eventoServicioId: string | null;
            /** Format: uuid */
            criaAnimalId: string | null;
            /** @enum {string|null} */
            facilidadParto: "Normal" | "Distocia" | "Cesárea" | "Aborto" | null;
            observaciones: string | null;
        };
        RegistrarPartoResponseDto: {
            evento: components["schemas"]["EventoWriteResponseDto"];
            parto: components["schemas"]["EventoPartoWriteResponseDto"];
        };
        RegistrarSecadoDto: {
            /**
             * @description Fecha de la suspensión real del ordeño (YYYY-MM-DD). No puede ser futura; puede diferir de la fecha de secado calculada.
             * @example 2026-08-10
             */
            fechaEvento: string;
            /**
             * @description Observaciones o tratamiento de sellado/terapia de secado intramamaria aplicada
             * @example Aplicada infusión de secado en los 4 cuartos + sellador de pezones
             */
            notas?: string;
            /** @description ID de evento anterior si este secado es una corrección */
            eventoCorrigeId?: string;
        };
        EventoSecadoWriteResponseDto: {
            /** Format: uuid */
            eventoId: string;
        };
        RegistrarSecadoResponseDto: {
            evento: components["schemas"]["EventoWriteResponseDto"];
            secado: components["schemas"]["EventoSecadoWriteResponseDto"];
        };
        ResumenServicioActivoDto: {
            eventoId: string;
            /** @example 2026-09-16 */
            fechaServicio: string;
            /** @example Inseminación Artificial */
            tipoServicio: string;
            /** @example Titan (CRC-B-001) */
            toroOPajilla: string;
            responsable: string | null;
            /**
             * @description Fecha probable de parto
             * @example 2026-06-24
             */
            fpp: string;
            /**
             * @description Servicio + 40 días
             * @example 2026-10-26
             */
            palpacionFecha: string;
            /**
             * @description FPP - 60 días
             * @example 2026-04-25
             */
            secadoFecha: string;
            /**
             * @description FPP - 15 días
             * @example 2026-06-09
             */
            avisoPartoFecha: string;
            /**
             * @description FPP - 3 días
             * @example 2026-06-21
             */
            avisoPartoUrgenteFecha: string;
            notas: string | null;
        };
        ResumenDiagnosticoActivoDto: {
            eventoId: string;
            /** @example 2026-10-26 */
            fecha: string;
            /** @enum {string} */
            metodo: "Palpación" | "Ecografía" | "PAG";
            /** @enum {string} */
            resultado: "Preñada" | "Vacía";
            eventoServicioId: string;
        };
        ResumenPartoActivoDto: {
            eventoId: string;
            /** @example 2026-06-22 */
            fecha: string;
            /** Format: uuid */
            criaAnimalId: string | null;
            /** @enum {string|null} */
            facilidadParto: "Normal" | "Distocia" | "Cesárea" | "Aborto" | null;
        };
        ResumenSecadoActivoDto: {
            eventoId: string;
            /** @example 2026-04-25 */
            fecha: string;
        };
        HitoReproductivoDto: {
            /**
             * @description "Aviso Parto" es FPP-15 y "Aviso Parto Urgente" es FPP-3. Son dos alertas distintas a propósito.
             * @enum {string}
             */
            tipo: "Palpación" | "Secado" | "Aviso Parto" | "Aviso Parto Urgente" | "Parto FPP";
            /**
             * @description Fecha del hito (YYYY-MM-DD)
             * @example 2026-10-15
             */
            fecha: string;
            /**
             * @description Días desde hoy. Negativo si el hito ya venció.
             * @example 12
             */
            diasRestantes: number;
            /**
             * @description true solo en el aviso de FPP-3 días
             * @example false
             */
            urgente: boolean;
        };
        EstadoReproductivoResponseDto: {
            animalId: string;
            /** @example 101 */
            areteInterno: string;
            /** @example Hembra */
            sexo: string;
            /** @example Holstein */
            razaNombre?: string;
            /**
             * @description Días de gestación de la raza; base del cálculo de la FPP
             * @example 281
             */
            diasGestacionRaza?: number;
            /**
             * @description Estado derivado del historial de eventos. Nunca se guarda ni se edita a mano.
             * @enum {string}
             */
            estadoActual: "Vacía" | "Servida" | "Preñada" | "En Secado";
            /**
             * @description Días transcurridos desde el evento que dejó al animal en este estado
             * @example 15
             */
            diasEnEstado?: number;
            servicioActivo?: components["schemas"]["ResumenServicioActivoDto"];
            ultimoDiagnostico?: components["schemas"]["ResumenDiagnosticoActivoDto"];
            ultimoParto?: components["schemas"]["ResumenPartoActivoDto"];
            ultimoSecado?: components["schemas"]["ResumenSecadoActivoDto"];
            proximosHitos: components["schemas"]["HitoReproductivoDto"][];
            /** @description Inconsistencias detectadas al derivar el estado, por ejemplo un evento sin su fila de detalle. */
            advertencias: string[];
        };
        EventoReproductivoHistorialDto: {
            eventoId: string;
            /** @enum {string} */
            tipo: "SERVICIO" | "DIAGNOSTICO" | "PARTO" | "SECADO";
            /**
             * @description Cuándo ocurrió en la realidad
             * @example 2026-09-16
             */
            fechaEvento: string;
            /**
             * Format: date-time
             * @description Cuándo se escribió en el sistema
             */
            fechaRegistro: string;
            usuarioId: string;
            /**
             * @description true si un evento posterior lo corrigió. Los eventos revertidos se incluyen en el historial, marcados: el registro es append-only y una corrección tiene que poder verse.
             * @example false
             */
            revertido: boolean;
            /**
             * Format: uuid
             * @description Si este evento corrige a otro, el id del corregido.
             */
            eventoCorrigeId: string | null;
            notas: string | null;
            /** @description Detalle propio del tipo de evento. SECADO no tiene detalle adicional, por eso puede venir nulo. */
            detalle: (components["schemas"]["DetalleServicioDto"] | components["schemas"]["DetalleDiagnosticoDto"] | components["schemas"]["DetallePartoDto"]) | null;
        };
        ProximoEventoReproductivoDto: {
            animalId: string;
            /** @example 101 */
            arete: string;
            /** @example Paloma */
            nombre: string;
            /**
             * @description "Parto FPP" se publica como "Parto" en este feed.
             * @enum {string}
             */
            tipo: "Palpación" | "Secado" | "Aviso Parto" | "Aviso Parto Urgente" | "Parto";
            /** @example 2026-10-26 */
            fecha: string;
            /** @example 12 */
            diasRestantes: number;
            /** @example false */
            urgente: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getPerfil: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil de usuario y finca */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponseDto"];
                };
            };
            /** @description Token ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_invitarUsuario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_confirmarInvitacion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmInvitationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogosController_findAllRazas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de razas ordenado por nombre */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, inválido o sin claims de tenant */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnimalesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnimalesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnimalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnimalesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnimalesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAnimalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnimalesController_darDeBaja: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BajaAnimalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnimalesController_getDocumentos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoAnimalResponseDto"][];
                };
            };
            /** @description Animal no encontrado en esta finca */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnimalesController_createDocumento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDocumentoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentoAnimalResponseDto"];
                };
            };
            /** @description Ruta, categoría o archivo inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rol o ruta de archivo no autorizados */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Animal no encontrado en esta finca */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El objeto ya está registrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PesajesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePesajeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PesajesController_findAllByAnimal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TratamientosController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTratamientoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TratamientosController_getEstadoSanitario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TratamientosController_findAllByAnimal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                animalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TratamientosController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTratamientoDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SanitaryController_getMedicamentos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token ausente, inválido o sin claims de tenant */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SanitaryController_getPadecimientos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token ausente, inválido o sin claims de tenant */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PotrerosController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PotrerosController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePotreroDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PotrerosController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PotrerosController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PotrerosController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePotreroDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PotrerosController_asignarAnimales: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AsignarAnimalesDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReproductiveController_registrarServicio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID del animal hembra */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarServicioDto"];
            };
        };
        responses: {
            /** @description Servicio registrado. Devuelve el evento, su detalle y los hitos calculados. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrarServicioResponseDto"];
                };
            };
            /** @description Animal macho, raza sin días de gestación configurados, fecha futura o datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, inválido o sin claims de tenant */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El rol autenticado no está autorizado para registrar servicios */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Animal no encontrado en esta finca */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReproductiveController_registrarDiagnostico: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID del animal hembra */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarDiagnosticoDto"];
            };
        };
        responses: {
            /** @description Diagnóstico registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrarDiagnosticoResponseDto"];
                };
            };
            /** @description Animal macho, fecha futura, o método/resultado inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, inválido o sin claims de tenant */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El rol peón no puede registrar diagnósticos */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Animal o servicio previo no encontrado en esta finca */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReproductiveController_registrarParto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID de la madre */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarPartoDto"];
            };
        };
        responses: {
            /** @description Parto registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrarPartoResponseDto"];
                };
            };
            /** @description Animal macho, fecha futura, o el animal no está en estado Preñada / En Secado */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, inválido o sin claims de tenant */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El rol autenticado no está autorizado para registrar partos */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Madre, cría o servicio asociado no encontrado en esta finca */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReproductiveController_registrarSecado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID del animal hembra */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarSecadoDto"];
            };
        };
        responses: {
            /** @description Secado registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrarSecadoResponseDto"];
                };
            };
            /** @description Animal macho, fecha futura o datos inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, inválido o sin claims de tenant */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El rol peón no puede registrar secados */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Animal no encontrado en esta finca */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReproductiveController_obtenerEstadoReproductivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID del animal */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado reproductivo derivado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoReproductivoResponseDto"];
                };
            };
            /** @description El animal es macho y no tiene ciclo reproductivo */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, inválido o sin claims de tenant */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Animal no encontrado en esta finca */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReproductiveController_obtenerHistorialReproductivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID del animal */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historial en orden cronológico ascendente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoReproductivoHistorialDto"][];
                };
            };
            /** @description Token ausente, inválido o sin claims de tenant */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Animal no encontrado en esta finca */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReproductiveController_obtenerProximosEventos: {
        parameters: {
            query?: {
                /** @description Cuántos días hacia adelante mirar. El feed incluye además los hitos vencidos en los últimos 7 días, porque siguen siendo tareas pendientes. */
                diasVentana?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista ordenada por días restantes, ascendente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProximoEventoReproductivoDto"][];
                };
            };
            /** @description diasVentana fuera del rango permitido (1-365) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, inválido o sin claims de tenant */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
